export enum ActionType {
    SendACommand = 'command',
    ShowANotice = 'notify',
    DesktopNotification = 'comnotificationmand',
    PlayASound = 'sound',
    Wait = 'wait',
    WaitFor = 'waitfor',
    ModifyVariable = 'variable',
    If = 'if',
    Repeat = 'repeat',
    Label = 'label',
    JumpToLabel = 'goto',
    Stop = 'stop',
    ModifyAButton = 'button',
    DisableThisReflex = 'disableme',
    DisableReflex = 'disable',
    EnableReflex = 'enable',
    CallFunction = 'function',
    ExecuteScript = 'script'
}
